backend:
  name: github
  repo: wslyvh/netlify-cms-i18n
  branch: main

media_folder: static/assets
public_folder: /assets

i18n:
  structure: multiple_files
  locales: [en, es]
  default_locale: en

collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    i18n: true
    fields:
      - { name: path, label: Path, widget: string, i18n: duplicate }
      - { name: title, label: Title, widget: string, i18n: true }
      - { name: body, label: Body, widget: markdown, i18n: true }